### PR TITLE
add some params for more flexibility

### PR DESCRIPTION
**Pull request by chinlung**
Add below params :
'ftps' => true, // use ftps:// with implicit TLS or ftp:// with explicit TLS
'passive' => true, // default use PASV mode
'skipPasvIp' => true, // ignore the IP address in the PASV response 
'verbose' => false // set verbose mode on/off

### CODE REVIEW

**Comment by chinlung** [comment]
I don't know why can't pass travis-ci check, but in my environment is test OK.
Maybe could you please check it, thanks

**Comment by Pchol** [comment]
good work!

**Comment by yapsr** [comment]
@vyuldashev  Could you please merge this request? I need the ftps config option.

**Comment by yapsr** [comment]
@chinlung Thank you. I hope @vyuldashev can merge this soon.

**Pull request merged**
